export const initialTools = [
  {
    id: 1,
    code: 'T-001',
    name: 'Martillo Demoledor',
    type: 'electric',
    status: 'assigned',
    responsible: 'Juan Pérez',
    assignmentDate: '2023-05-15',
    nextMaintenance: '2026-11-15',
    location: 'Almacén Central',
    notes: 'Revisar anclajes mensualmente',
    maintenanceHistory: ['2023-05-10', '2023-02-15'],
  },
  {
    id: 2,
    code: 'T-002',
    name: 'Llave Stillson 24"',
    type: 'manual',
    status: 'active',
    responsible: '',
    assignmentDate: '',
    nextMaintenance: '2025-09-20',
    location: 'Almacén Sur',
    notes: 'Última revisión OK',
    maintenanceHistory: ['2023-03-20'],
  },
  {
    id: 3,
    code: 'T-003',
    name: 'Nivel Láser',
    type: 'measuring',
    status: 'maintenance',
    responsible: 'Carlos García',
    assignmentDate: '2023-06-02',
    nextMaintenance: '2025-07-30',
    location: 'Taller Mantenimiento',
    notes: 'Batería agotada, enviar a servicio técnico',
    maintenanceHistory: ['2023-04-15', '2023-01-10'],
  },
];
